# =========================================================
# TrafficIQ Application
# =========================================================

spring.application.name=traffiq-backend


# =========================================================
# PostgreSQL 18
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/traffiq
spring.datasource.username=postgres
spring.datasource.password=1407
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# JPA / Hibernate
# =========================================================

spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true

trafficiq.matching.window-minutes=30
server.port=8080